name:                grannies-coockie
version:             0.1.0.0
github:              "github.com/bearmond1/grannies-coockie"
license:             BSD3
author:              "bearmond"
maintainer:          "madorrange@gmail.com"
copyright:           "2023 bearmond"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/grannies-coockie#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
#- aeson-pretty
- array
- bytestring
- base64-bytestring
- cryptonite
- containers
#- esqueleto
- monad-logger
- persistent
- persistent-postgresql
- time
- text
- http-types
- http-client
- mtl
- mmorph
#- either
- servant 
- servant-docs
#- servant-openapi3
- servant-server
#- servant-util
- servant-multipart
- random
- record-hasfield
#- lens
#- optics
- split
#- servant-swagger
#- swagger2
- warp
- wai


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DuplicateRecordFields
- LambdaCase
- FlexibleContexts
- OverloadedStrings
- OverloadedRecordDot
- OverloadedLists
- StrictData
- ScopedTypeVariables
- NamedFieldPuns
- RecordWildCards
- TypeApplications
- TypeFamilies
- TypeOperators
- FlexibleInstances
- MultiParamTypeClasses
- PartialTypeSignatures


library:
  dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)
  source-dirs: src

executables:
  grannies-coockie-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grannies-coockie

tests:
  grannies-coockie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grannies-coockie
